schedules:
  - title: "[INFOCOM'23] ResMap: Exploiting Sparse Residual Feature Map for Accelerating Cross-Edge Video Analytics"
    conf: "INFOCOM'23"
    presenter: 赵文哲
    date: Apr 19, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/Y0rS7inWP9QL
      - title: Slides
        url: /slides/2023.4.19-组会报告-赵文哲.pdf
  - title: "[INFOCOM'23] AccDecoder: Accelerated Decoding for Neural-enhanced Video Analytics"
    conf: "INFOCOM'23"
    presenter: 赵文哲
    date: Apr 19, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/Y0rS7inWP9QL
      - title: Slides
        url: /slides/2023.4.19-组会报告-赵文哲.pdf

  - title: "[NSDI'22] Swift: Adaptive Video Streaming with Layered Neural Codecs"
    conf: "NSDI'22"
    presenter: 陈柏均
    date: Mar 22, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/zzFuBnZoHXp9
      - title: Slides
        url: /slides/2023.3.21-组会报告-陈柏均.pdf

  - title: "[INFOCOM'22] Batch Adaptative Streaming for Video Analytics"
    conf: "INFOCOM'22"
    presenter: 徐振轩
    date: December 28, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/w0AKlQKsnozi
      - title: Slides
        url: /slides/2022_12_28徐振轩_组会报告.pdf

upcomings:
  - "Mengyang Liu will present an OSDI'22 paper on Monday, Feb 6, 2023, at 7:00 p.m. (GMT+8)."

# Refer to https://fontawesome.com/v4/icons/ for an ideal icon.
# The default icon is fa-thumb-tack.
links:
  - title: Paper Pool is here.
    url: https://docs.qq.com/sheet/DYnFsaHNWVkFieGpk?tab=BB08J2
    icon: fa-paperclip

  - title: Guide is here.
    url: /files/Guidance.pdf
    icon: fa-compass

  - title: How to contribute to this website?
    url: https://github.com/SEU-EVG/SEU-EVG.github.io/blob/master/How-To-Update.md
    icon: fa-github

  - title: Upload a new schedule.
    url: https://github.com/SEU-EVG/SEU-EVG.github.io/edit/master/configs/config.yml
    icon: fa-pencil

# Refer to https://www.w3schools.com/w3css/w3css_colors.asp for an ideal color.
# The default primary color is teal, and the default accent color is pale-green.
layout:
  schedulesPerPage: 5
  primaryColor: teal
  accentColor: light-gray

global:
  header: Edge Video Reading Group @ SEU
  footer: 2023 SEU-EVG. Powered by Jekyll and GitHub Pages.
